{
 "title": "Quest Logger Microservices",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Minute by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (rate(app_request_count[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_active_requests", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le, service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status, service) (rate(app_request_count{http_status=~\"5..\"}[1m]))",
     "legendFormat": "{{service}} - {{http_status}}"
    }
   ]
  }
 ]
}