from setuptools import setup, find_packages

setup(
    name="quest-logger-common",
    version="0.1.0",
    description="Common libraries for Quest Logger microservices",
    author="Quest Logger Team",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "pydantic>=2.0.0",
        "pydantic-settings>=2.0.0",
        "sqlalchemy>=2.0.0",
        "psycopg2-binary>=2.9.9",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.6",
        "alembic>=1.12.0",
        "pydantic[email]>=2.0.0",
        "aio-pika>=9.3.0",
        "redis>=5.0.1",
        "prometheus-client>=0.17.1",
        "opentelemetry-api>=1.20.0",
        "opentelemetry-sdk>=1.20.0",
        "opentelemetry-instrumentation-fastapi>=0.41b0",
        "tenacity>=8.2.3",
        "httpx>=0.24.1",
    ],
)